name: Deploy to GitHub Pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build & Deploy
        run: |
          echo "Building website..."
          mkdir public
          echo "<h1>Hello, GitHub Pages!</h1>" > public/index.html
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add public
          git commit -m "Deploy to GitHub Pages"
          git push origin master
